// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl1wdRU9hUBgQbmgkut3rBwQ5GNqewMq0',
    appId: '1:1052048950734:web:1bb3ddfc6e3c5f6e90579f',
    messagingSenderId: '1052048950734',
    projectId: 'almohandes',
    authDomain: 'almohandes.firebaseapp.com',
    storageBucket: 'almohandes.appspot.com',
    measurementId: 'G-BNXMH86RYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaigX8wEJKW6T725SsiLsLTz8dXNjpKus',
    appId: '1:1052048950734:android:c7a1d11ffa294c3f90579f',
    messagingSenderId: '1052048950734',
    projectId: 'almohandes',
    storageBucket: 'almohandes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_8bIg3KwjozpZcW8cYVhpaEJVzvFlVaY',
    appId: '1:1052048950734:ios:d254649178678f5e90579f',
    messagingSenderId: '1052048950734',
    projectId: 'almohandes',
    storageBucket: 'almohandes.appspot.com',
    androidClientId: '1052048950734-76j35d66nhm5qakn99c9nk08ofs3vf3u.apps.googleusercontent.com',
    iosClientId: '1052048950734-0q8l0fujss5h34b7ps1mduhqh5jofc0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.almohandesEstate',
  );
}
